### ISSUE TITLE
pg v10.3 ERROR:  function pg_last_xlog_receive_location() does not exist

### ISSUE THREAD

**Issue by seadba** [NikolayS/postgres_dba#12]
Hello, cool tool - is there a version that works with v10?

Type your choice and press <Enter>:
1
psql.bin:/instance1/postgres/10/sitewatch/test/postgres_dba/sql/1_basic.sql:53:ERROR:  function pg_last_xlog_receive_location() does not exist
LINE 13:           when pg_last_xlog_receive_location() = pg_last_xlo...
                        ^
HINT:  No function matches the given name and argument types. You might need toadd explicit type casts.
Press <Enter> to continue…

**Comment by NikolayS** [comment]
hi @seadba thanks for catching this! 

Just fixed it and committed to master, please check. Now report 1 has to work both with postgres 10 and earlier versions.

**Comment by seadba** [comment]
excellent - works well , thanks very much for the fast response - great tool
