### ISSUE TITLE
psql:/var/lib/postgresql/postgres_dba/start.psql:22: unrecognized value ":postgres_dba_wide" for "\if expression": Boolean expected

### ISSUE THREAD

**Issue by vjfernan** [NikolayS/postgres_dba#19]
Hi Nikolay,

In a server with postgresql 9.5.12 and postgresql-client 10.3 when I type :dba <enter> I get this error in the menu:

my_db=# :dba
SET
RESET
Menu:
   0 – Node & Current DB Information: master/replica, lag, DB size, tmp files, etc
   1 – Databases: Size, Statistics
   2 – Table Sizes
   3 – Load Profile
  a1 – Current Activity: count of current connections grouped by database, user name, state
  b1 – Tables Bloat, rough estimation
  b2 – B-tree Indexes Bloat, rough estimation
  b3 – Tables Bloat, more precise (requires pgstattuple extension; expensive)
  b4 – B-tree Indexes Bloat, more precise (requires pgstattuple extension; expensive)
  b5 – Tables and Columns Without Stats (so bloat cannot be estimated)
  i1 – Unused/Rarely Used Indexes
  i2 – Unused/Redundant Indexes Do & Undo Migration DDL
  i3 – FKs with Missing/Bad Indexes
  p1 – [EXPERIMENTAL] Alignment Padding. How many bytes can be saved if columns are ordered better?
  s1 – Slowest Queries, by Total Time (requires pg_stat_statements extension)
  s2 – Slowest Queries Report (requires pg_stat_statements)
  t1 – Postgres parameters tuning
  v1 – Vacuum: Current Activity
**psql:/var/lib/postgresql/sistemas/postgres_dba/start.psql:22: unrecognized value ":postgres_dba_wide" for "\if expression": Boolean expected**
   x – Turn Wide Mode ON (currently OFF): show more details, more columns
   q – Quit

Type your choice and press <Enter>:

Regards.

**Comment by NikolayS** [comment]
Thank you!

Could you please check that in branch pg95_fix this issue is resolved?

**Comment by vjfernan** [comment]
Hi Nikolay,

The issue is resolved in brach pg95_fix.

Excellent tool.

Thank you.

**Comment by NikolayS** [comment]
Thank you.
Let me know if you find any other issues with 9.5.
