### ISSUE TITLE
Issue with query b1 on postgres 12

### ISSUE THREAD

**Issue by gowtham500** [NikolayS/postgres_dba#43]
Hello Nicholas,

Thanks for this awesome tool. This issue is with option  b1 – Tables Bloat, rough estimation.
I am running on postgres 12.1 and got this error
```
psql:/var/lib/pgsql/postgres_dba/sql/b1_table_estimation.sql:99: ERROR:  column tbl.relhasoids does not exist
LINE 19:       + case when tbl.relhasoids then 4 else 0 end as tpl_hd...
```

Can you please include support for postgres 12

**Comment by NikolayS** [comment]
Thank you @gowtham500 for this bug report.

Fixed this error, as well as the problem with p1 report in Postgres 12:  https://github.com/NikolayS/postgres_dba/pull/44

Merged to master, please test.
