### ISSUE TITLE
s1 problem, needs conditional for the order by

### ISSUE THREAD

**Issue by KiriakosGeorgiou** [NikolayS/postgres_dba#59]
s1 gives the following error on a v12 server:

LINE 31: order by sum(total_exec_time) desc

needs conditional to use total_time

**Comment by NikolayS** [comment]
@KiriakosGeorgiou thank you! fixed in https://github.com/NikolayS/postgres_dba/commit/a8654686a664a4f1fc1d5b09b9114eee465cfdc5. Please check.
